### ISSUE TITLE
[Feature Request] enhanced op_fetch_data_hdf5_file

### ISSUE THREAD

**Issue by basegpu** [OP2/OP2-Common#114]
The current API of the op2_hdf5 library `c/src/externlib/op_hdf5.c` contains the function
~~~c
void op_fetch_data_hdf5_file(op_dat dat, char const *file_name)
~~~

The name of the dataset in the h5-file is taken from `dat->name`.  The following enhancements are desired:

* `op_fetch_data_hdf5_file` is not capable of dealing with `dat->name` representing a path inside the h5-file (string with '/'s). Since the path functionality is there when declaring an `op_dat` with `op_decl_dat_hdf5`, it would be nice to have the same behaviour when fetching the data to an h5-container.
* An additional function `void op_fetch_data_hdf5_file(op_dat dat, char const *file_name, char const *dataset_name)` would increase the flexibility of dumping `op_dat` to the h5-container, where `dataset_name` is a freely chosen path inside the h5-file of the dataset.

**Comment by gihanmudalige** [comment]
I am looking into this now. Do you have a small example that I can use to verify functionality ?

**Comment by basegpu** [comment]
I have no small example ready. But I think the functionality can be verified independent of the application since the call `op_fetch_data_hdf5_file(dat_to_be_written, "filename.h5", "path/to/dataset")` can be simply put wherever in any existing testcase.

**Comment by gihanmudalige** [comment]
OK.
Just to double check, have you tested the path functionality when declaring an op_dat with op_decl_dat_hdf5 ?

This is just so that I can test the full functionality - i.e. both reading and writing using a path in the op_dat->name.

**Comment by basegpu** [comment]
yes, the path functionality is enabled when reading via `op_decl_dat_hdf5`, i.e. if `op_dat->name` shows a path pattern, the h5 dataset is read from the according h5 group.

**Comment by gihanmudalige** [comment]
OK, I have got the first feature requested above done in the branch feature/hdf5_dataset_path. 

I am not sure whether we need the second feature (i.e. the additional function void op_fetch_data_hdf5_file(op_dat dat, char const *file_name, char const *dataset_name). The reason being the path in dataset_name conflicting with path in dat->name. 

@reguly  what do you think ?

**Comment by basegpu** [comment]
many thx @gihanmudalige !
for clarification: the main application for the second feature would be the writing of same `op_dat` at different simulation times (as result), therefore different dataset names are needed to avoid overwriting of previous times.

**Comment by reguly** [comment]
I think this should be doable easily on the backend side (temporarily changing the name of the dataset). We just need to document clearly, that that will be the new name of the dataset in the file. It's kind of like a 'save as' feature.

**Comment by basegpu** [comment]
ok, I was not aware about this option:
> temporarily changing the name of the dataset

doing so, the flexibility is there!
I will run some tests on the branch *feature/hdf5_dataset_path* and give a feedback.

**Comment by basegpu** [comment]
I had a look to `op_hdf5.c`. As I understand, when calling
~~~c
op_fetch_data_hdf5_file(op_dat dat, char const *file_name)
~~~
then `dat->name` is used as name of the dataset. When calling
~~~c
op_fetch_data_hdf5_file_path(op_dat dat, char const *file_name, char const *path_name)
~~~
then `path_name` is used as name of the dataset. In both cases the dataset name can contain `/` to define a path inside the *.h5* file.
Would this application be correct?

**Comment by gihanmudalige** [comment]
Yes. 
Have a look at `OP2-Common/tree/feature/hdf5_dataset_path/apps/c/airfoil/airfoil_hdf5/dp/convert_mesh`
and `convert_mesh_mpi` you will see the use of `op_fetch_data_hdf5_file(op_dat dat, char const *file_name)`
As you will see, the name can contain `/`

I am yet to add a test for `op_fetch_data_hdf5_file_path(op_dat dat, char const *file_name, char const *path_name)`

**Comment by basegpu** [comment]
ok, both functions work with setting the dataset name e.g.
~~~c
char name[128];
sprintf(name,"states_%07i", (int)(time*100.0));
op_fetch_data_hdf5_file_path(dat_out, filename, name);
~~~
But when adding a path to the name, such as
~~~c
sprintf(name,"/results/states_%07i", (int)(time*100.0));
~~~
then the writing fails with
> File test.h5 exists .... checking for dataset and path/results/states_0000000 in file
op_dat /results/states_0000000 exists in the file ... updating data
data set /results/states_0000000 on file test.h5 does not have attribute 'size' -- cannot check size ... aborting

actually, the dataset `/results/states_000000` does not exist in `test.h5`...

**Comment by gihanmudalige** [comment]
Let me add a test to convert_mesh and see if I can replicate the above.

**Comment by gihanmudalige** [comment]
Ok, try now. I have also added your test case to convert_mesh.

**Comment by gihanmudalige** [comment]
Branch #feature/hdf5_dataset_path is now ready as a solution to the above issue. Please test and see if there are any further changes  required

**Comment by basegpu** [comment]
tested with branch `master` and everything works as expected.
many thx!
