### ISSUE TITLE
Feature Request - C Wrapper for Fortran?

### ISSUE THREAD

**Issue by OniDaito** [OP2/OP2-Common#83]
Hello there. I was wondering if its possible to call C based OP2 functions from Fortran? Although it should be possible to call CUDA and C functions from Fortran, I wonder if the magic of OP2 automatic code generation might upset my plan to write a wrapper? Basically, I am writing in Fortran but I don't have the portland cuda compiler. Cheers!

**Comment by reguly** [comment]
Hi Benjamin!

Unfortunately it would break a great variety of things (such as the host side’s handling of function pointers, the handling of global constants, etc.) so this is not something that is feasible I think. However, for non-commercial purposes I think you can actually get a licence for the PGI compiler, when you download the OpenACC toolkit via the NVIDIA website, you have the option to ask for one.

Cheers,
István

**Comment by OniDaito** [comment]
Excellent! I'd not hears of the OpenACC toolkit - in the process of getting it, and its 90 day, 1 year licence. 
Cheers!
Ben
